// <auto-generated />
using System;
using LeaderTrip.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LeaderTrip.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LeaderTripDbContext))]
    [Migration("20260816051747_AuthAndSavedTrips")]
    partial class AuthAndSavedTrips
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LeaderTrip.Infrastructure.Persistence.CityRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<int>("Amenities")
                        .HasColumnType("integer")
                        .HasColumnName("amenities");

                    b.Property<string>("Climate")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("climate");

                    b.Property<decimal>("CostIndex")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("cost_index");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("province");

                    b.HasKey("Id")
                        .HasName("pk_cities");

                    b.HasIndex("Province")
                        .HasDatabaseName("ix_cities_province");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("LeaderTrip.Infrastructure.Persistence.PoiRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<int[]>("BestMonths")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("best_months");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<string>("CityId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("city_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("difficulty");

                    b.Property<bool>("Indoor")
                        .HasColumnType("boolean")
                        .HasColumnName("indoor");

                    b.Property<bool>("KidFriendly")
                        .HasColumnType("boolean")
                        .HasColumnName("kid_friendly");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.Property<int>("MinAge")
                        .HasColumnType("integer")
                        .HasColumnName("min_age");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<bool>("NightSuitable")
                        .HasColumnType("boolean")
                        .HasColumnName("night_suitable");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision")
                        .HasColumnName("rating");

                    b.Property<string>("RequiredVehicle")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("required_vehicle");

                    b.Property<bool>("SeniorFriendly")
                        .HasColumnType("boolean")
                        .HasColumnName("senior_friendly");

                    b.Property<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<decimal>("Ticket")
                        .HasPrecision(14)
                        .HasColumnType("numeric(14,0)")
                        .HasColumnName("ticket");

                    b.Property<int>("VisitMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("visit_minutes");

                    b.HasKey("Id")
                        .HasName("pk_pois");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_pois_category");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_pois_city_id");

                    b.ToTable("pois", (string)null);
                });

            modelBuilder.Entity("LeaderTrip.Infrastructure.Persistence.PriceBookRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.HasKey("Id")
                        .HasName("pk_price_books");

                    b.HasIndex("EffectiveFrom")
                        .HasDatabaseName("ix_price_books_effective_from");

                    b.ToTable("price_books", (string)null);
                });

            modelBuilder.Entity("LeaderTrip.Infrastructure.Persistence.SavedTripRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_saved_trips");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_saved_trips_user_id");

                    b.ToTable("saved_trips", (string)null);
                });

            modelBuilder.Entity("LeaderTrip.Infrastructure.Persistence.SessionRow", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("TokenHash")
                        .HasName("pk_auth_sessions");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_auth_sessions_expires_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_auth_sessions_user_id");

                    b.ToTable("auth_sessions", (string)null);
                });

            modelBuilder.Entity("LeaderTrip.Infrastructure.Persistence.UserRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LeaderTrip.Infrastructure.Persistence.VehicleRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("class");

                    b.Property<double>("ConsumptionPer100Km")
                        .HasColumnType("double precision")
                        .HasColumnName("consumption_per100km");

                    b.Property<decimal>("DepreciationPerKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("depreciation_per_km");

                    b.Property<string>("Fuel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("fuel");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("label");

                    b.Property<string>("Offroad")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("offroad");

                    b.Property<int>("Seats")
                        .HasColumnType("integer")
                        .HasColumnName("seats");

                    b.Property<double>("SpeedFactor")
                        .HasColumnType("double precision")
                        .HasColumnName("speed_factor");

                    b.Property<decimal>("TollFactor")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("toll_factor");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("LeaderTrip.Infrastructure.Persistence.PoiRow", b =>
                {
                    b.HasOne("LeaderTrip.Infrastructure.Persistence.CityRow", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pois_cities_city_id");
                });
#pragma warning restore 612, 618
        }
    }
}
